### ISSUE TITLE
Release on pypi is broken

### ISSUE THREAD

**Issue by schuylerfried** [pyGSTio/pyGSTi#55]
Error when trying to import module functions:
```
  from pygsti.construction import make_lsgst_experiment_list, std1Q_XY, std1Q_XYI, std2Q_XYCNOT
  File "/home/schuyler/.conda/envs/arb-p/lib/python3.6/site-packages/pygsti/__init__.py", line 15, in <module>
    from . import report as rpt
  File "/home/schuyler/.conda/envs/arb-p/lib/python3.6/site-packages/pygsti/report/__init__.py", line 12, in <module>
    from .factory import *
  File "/home/schuyler/.conda/envs/arb-p/lib/python3.6/site-packages/pygsti/report/factory.py", line 26, in <module>
    from . import workspace as _ws
  File "/home/schuyler/.conda/envs/arb-p/lib/python3.6/site-packages/pygsti/report/workspace.py", line 26, in <module>
    from . import plotly_plot_ex as _plotly_ex
  File "/home/schuyler/.conda/envs/arb-p/lib/python3.6/site-packages/pygsti/report/plotly_plot_ex.py", line 11, in <module>
    from plotly.offline.offline import _plot_html
ImportError: cannot import name '_plot_html'
```

Turns out plotly released v3.8.0 like 11 hours ago, which removed this function `_plot_html_`. Easy fix is to pin the plotly version in your requirements.txt and setup.py, then tag and release a new version.

**Comment by schuylerfried** [comment]
Longer term fix would be to remove any calls to functions that start with _

**Comment by enielse** [comment]
Thanks for noting this issue - our automated tests picked this up earlier today and the pyGSTi beta branch has already been fixed to work with plotly v3.8.  As you suggested, we could hotfix the master branch by simply pinning the plotly version to 3.7, which I expect we'll do soon.  Let's leave this issue open until that happens.

As an aside, one good thing coming from all this is that the functionality that pyGSTi needs from plotly is now (as of v3.8) exposed through the public api (no underscore functions) -- previously we unfortunately needed to utilize the `_plot_html` function.  So pyGSTi will be less fragile to plotly updates in the future, and more robust in general because `_plot_html` was the _only_ underscore function imported in from an external package.

**Comment by enielse** [comment]
Just for completeness, this issue is temporarily fixed by pinning the plotly version in the [**Version 0.9.7.3 release**](https://github.com/pyGSTio/pyGSTi/releases/tag/v0.9.7.3), which is available through PyPI/pip now as well.  This pinning will be removed in future releases which will contain a more permanent fix.  I believe this solves the issue raised by schuylerfried an so I'll close the this issue.

**Comment by schuylerfried** [comment]
Thank you!
